"""Изменил даты с Даты на стр

Revision ID: 3710f9f9c408
Revises: f56243fb25d0
Create Date: 2025-09-25 12:14:40.495501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3710f9f9c408'
down_revision: Union[str, Sequence[str], None] = 'f56243fb25d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_words', 'r_1',
               existing_type=sa.DATE(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('user_words', 'r_2',
               existing_type=sa.DATE(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('user_words', 'r_3',
               existing_type=sa.DATE(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('user_words', 'r_4',
               existing_type=sa.DATE(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('user_words', 'r_5',
               existing_type=sa.DATE(),
               type_=sa.String(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_words', 'r_5',
               existing_type=sa.String(),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('user_words', 'r_4',
               existing_type=sa.String(),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('user_words', 'r_3',
               existing_type=sa.String(),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('user_words', 'r_2',
               existing_type=sa.String(),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('user_words', 'r_1',
               existing_type=sa.String(),
               type_=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
