"""Initial migration with user_words table

Revision ID: f56243fb25d0
Revises: 
Create Date: 2025-09-18 20:36:57.983073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f56243fb25d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('english_sentances', 'chat_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_foreign_key(None, 'english_sentances', 'user_words', ['chat_id'], ['user_id'])
    op.add_column('user_words', sa.Column('r_1', sa.Date(), nullable=True))
    op.add_column('user_words', sa.Column('r_2', sa.Date(), nullable=True))
    op.add_column('user_words', sa.Column('r_3', sa.Date(), nullable=True))
    op.add_column('user_words', sa.Column('r_4', sa.Date(), nullable=True))
    op.add_column('user_words', sa.Column('r_5', sa.Date(), nullable=True))
    op.alter_column('user_words', 'date_created',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_words', 'date_created',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)
    op.drop_column('user_words', 'r_5')
    op.drop_column('user_words', 'r_4')
    op.drop_column('user_words', 'r_3')
    op.drop_column('user_words', 'r_2')
    op.drop_column('user_words', 'r_1')
    op.drop_constraint(None, 'english_sentances', type_='foreignkey')
    op.alter_column('english_sentances', 'chat_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
